sudo: false
language: python
python:
  - "2.7"
branches:
  only:
    - master
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --yes conda
  - mkdir $HOME/opt/
  - cd $HOME/opt && git clone --quiet --depth 5 git@github.com:INM-6/h5py_wrapper.git
  - export PYTHONPATH=$HOME/opt/:$PYTHONPATH
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy nose h5py
script:
  - nosetests
