sudo: false
language: python
python:
  - "2.7"
  - "3.5"
branches:
  only:
    - master
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - cd ../ && git clone --quiet --depth 5 https://github.com/INM-6/h5py_wrapper.git && cd python-dicthash/
  - conda create --yes -n myenv python=$TRAVIS_PYTHON_VERSION
  - source activate myenv
  - pip install --upgrade pip
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy nose h5py
  - pip install --upgrade quantities future
script:
  - nosetests
